numpyはnpという名前でインポートされることがほとんどです

In [1]:
import numpy as np

numpyではarrayという配列で計算を行います  
ここでは[1, 2, 3, 4, 5]という要素をもったnumpyのarrayを用意しましょう

In [2]:
arr = np.array([1, 2, 3, 4, 5])

大きさはshapeでわかります

In [3]:
arr.shape

(5,)

arrayに対して足し算をしてみましょう

In [4]:
arr + 2

array([3, 4, 5, 6, 7])

すべての要素に+2されました  
これをブロードキャストといいます

足し算だけでなく、他の演算子でも同じようなことが起きます  
ルートをとってみましょう

In [5]:
np.sqrt(arr)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798])

リストと同様にスライスで要素を抽出できます  

In [6]:
arr[:2]

array([1, 2])

In [7]:
arr[3:5]

array([4, 5])

numpyのarange関数はよく使います  
arange関数を使って[0, 1, 2, 3, 4]という要素をもったarrayを簡単に作ることができます

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

arange関数にはstart, end, stepを指定できます  
[2, 4, 6, 8]という2ずつ数字が増えていくarrayは次のように作ることができます

In [9]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

linspace関数もよく使います  
linspace関数もstartからendまでのarrayを作る関数ですが、stepではなく要素の数を指定します  
ここでは0から3までを11分割したarrayを作ってみます

In [10]:
np.linspace(0, 3, 11)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8,  2.1,  2.4,  2.7,  3. ])

二次元のarrayも簡単に作れます

In [11]:
arr2 = np.array([[1, 3],
                 [5, 7]])
arr2

array([[1, 3],
       [5, 7]])

In [12]:
arr2.shape

(2, 2)

save関数でarrayを保存できます  
第一引数が保存する名前で、第二引数が保存するarrayです

In [13]:
np.save('test.npy', arr2)

読み込みはload関数でできます

In [14]:
np.load('test.npy')

array([[1, 3],
       [5, 7]])